version: "3"

services:
  geth_l2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - l2-node-data:/mnt/l2-node/l2:rw
    environment:
      - CLEAR_DATA_KEY
      - TARGET_GAS_LIMIT
      - VOLUME_PATH=/mnt/l2-node/l2
      - HOSTNAME=geth_l2
      - PORT=8545
      - NETWORK_ID=108
    ports:
      - 8545:8545

volumes:
  l2-node-data: