name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-lint-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build the Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build . --file Dockerfile.test -t geth_test

      - name: Run Lint & Test Docker Image
        run: docker run geth_test:latest
