name: Setup & Run Integration Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Setup & Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          git clone https://github.com/ethereum-optimism/optimism-integration.git \
              $HOME/optimism-integration
          cd $HOME/optimism-integration
          sed -i -Ee's#git@github.com:([^/]*)/(.*).git#https://github.com/\1/\2.git#' .gitmodules
          git submodule init
          git submodule update
          if [ -z $GITHUB_HEAD_REF ]; then
              GITHUB_HEAD_REF=${GITHUB_REF##*/}
          fi
          GIT_COMMIT=$(git rev-parse HEAD | head -c 8)
          echo "optimism-integration $GIT_COMMIT"
          ./docker/build.sh -s go-ethereum -b $GITHUB_HEAD_REF

      - name: Test
        run: |
          cd $HOME/optimism-integration
          GETH_L2_TAG=$GITHUB_HEAD_REF ./test.sh
